#DOCKER-COMPOSE FOR UNO TESTING
version: '3.1'

services:
  database:
    image: 'mongo'
    container_name: 'uno_dev_mongodb'
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: qwerty123